# Generated by Django 3.0.6 on 2021-12-14 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langanligi")),
                ('service', models.CharField(choices=[('1', 'CLICK'), ('2', 'PAYCOM')], default=1, max_length=10)),
                ('amount', models.CharField(max_length=20, verbose_name='Summasi')),
            ],
        ),
    ]
