# Generated by Django 3.0.6 on 2021-12-14 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savol',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.Video'),
        ),
        migrations.AddField(
            model_name='resultquiz',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_result_answer', to='quiz.Javob'),
        ),
        migrations.AddField(
            model_name='resultquiz',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_result_question', to='quiz.Savol'),
        ),
        migrations.AddField(
            model_name='resultquiz',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_result_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultjavob',
            name='bilet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultjavob_bilet', to='quiz.Bilet'),
        ),
        migrations.AddField(
            model_name='resultjavob',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultjavob_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_answer', to='quiz.Javob'),
        ),
        migrations.AddField(
            model_name='result',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_question', to='quiz.Savol'),
        ),
        migrations.AddField(
            model_name='result',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.Video'),
        ),
        migrations.AddField(
            model_name='javob',
            name='savol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='quiz.Savol'),
        ),
        migrations.AddField(
            model_name='checktestcolor',
            name='bilet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Bilet'),
        ),
        migrations.AddField(
            model_name='checktestcolor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_bilet_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='quiz.Question'),
        ),
    ]
