# Generated by Django 3.0.6 on 2020-12-26 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0014_auto_20201226_1151'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Model nomi')),
                ('is_nationality', models.BooleanField(default=True, verbose_name='Milliyligi')),
            ],
            options={
                'verbose_name': 'Avtomobil modeli',
                'verbose_name_plural': 'Avtomobil modellari',
            },
        ),
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(auto_now=True)),
                ('training_time', models.DateTimeField(verbose_name="Amaliy mashg'ulotga yozilgan vaqti")),
                ('status', models.BooleanField(default=True, verbose_name="Amaliy mashg'ulot holati")),
                ('cancel', models.BooleanField(default=False, verbose_name='Bekor qilinganligi')),
                ('reason_for_cancel', models.CharField(max_length=255, verbose_name="Amaliy mashg'ulotni bekor qilish sababi")),
                ('by_whom', models.CharField(choices=[('1', 'Instruktor'), ('2', "O'quvchi")], max_length=255, verbose_name='Kim tomonidan bekor qilinganligi')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_instructor', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
                ('pupil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practical_pupil', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "Amaliy mashg'ulot",
                'verbose_name_plural': "Amaliy mashg'ulotlar",
            },
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('instruktor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_of_week_instruktor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dam olish kuni',
                'verbose_name_plural': 'Dam olish kunlari',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_number', models.CharField(max_length=255)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Instruktor')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practical.CarModel')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Region')),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
            },
        ),
    ]
