# Generated by Django 3.0.6 on 2020-12-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_rental',
            field=models.BooleanField(default=False),
        ),
    ]
