# Generated by Django 3.0.6 on 2020-12-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practical', '0002_car_is_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_rental',
            field=models.BooleanField(default=False, verbose_name='Ijara avtomobil'),
        ),
    ]
