# Generated by Django 3.0.6 on 2020-12-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20201226_1501'),
        ('practical', '0003_auto_20201226_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practical.CarModel', verbose_name='Avtomobil modeli'),
        ),
        migrations.AlterField(
            model_name='car',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Region', verbose_name='Viloyatni tanlang'),
        ),
        migrations.AlterField(
            model_name='car',
            name='state_number',
            field=models.CharField(max_length=255, verbose_name='Davlat raqam belgisi'),
        ),
    ]
