# Generated by Django 3.0.6 on 2021-12-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
