# Generated by Django 3.0.6 on 2022-01-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220126_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_date',
            field=models.DateTimeField(verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updated_date',
            field=models.DateTimeField(blank=True, verbose_name='Tahrirlangan vaqti'),
        ),
    ]
