# Generated by Django 3.0.6 on 2022-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220129_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tahrirlangan vaqti'),
        ),
    ]
