# Generated by Django 3.0.6 on 2021-12-14 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_number', models.CharField(max_length=255, verbose_name='Davlat raqam belgisi')),
                ('is_rental', models.BooleanField(default=False, verbose_name='Ijara avtomobil')),
                ('price', models.IntegerField(max_length=30, verbose_name='Avtomobil narxi')),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Model nomi')),
                ('is_nationality', models.BooleanField(default=True, verbose_name='Milliyligi')),
            ],
            options={
                'verbose_name': 'Avtomobil modeli',
                'verbose_name_plural': 'Avtomobil modellari',
            },
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
            options={
                'verbose_name': 'Dam olish kuni',
                'verbose_name_plural': 'Dam olish kunlari',
            },
        ),
        migrations.CreateModel(
            name='PaymentForPractical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(max_length=12, verbose_name="To'lov summasi")),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': "Vajdeniya uchun to'lov",
                'verbose_name_plural': "Vajdeniya uchun to'lovlar",
            },
        ),
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('training_time', models.DateTimeField(verbose_name="Amaliy mashg'ulotga yozilgan vaqti")),
                ('status', models.BooleanField(default=True, verbose_name="Amaliy mashg'ulot holati")),
                ('cancel', models.BooleanField(default=False, verbose_name='Bekor qilinganligi')),
                ('reason_for_cancel', models.CharField(max_length=255, verbose_name="Amaliy mashg'ulotni bekor qilish sababi")),
                ('by_whom', models.CharField(choices=[('1', 'Instruktor'), ('2', "O'quvchi")], max_length=255, verbose_name='Kim tomonidan bekor qilinganligi')),
                ('is_partnership', models.BooleanField(default=True, verbose_name='Sherik bilan')),
                ('is_payment', models.BooleanField(default=False, verbose_name="To'lov to'langanligi")),
                ('is_prepaid', models.BooleanField(default=True, verbose_name="To'lov avvaldan")),
                ('is_postpaid', models.BooleanField(default=False, verbose_name="To'lov bajarilganidan so'ng")),
                ('is_bonus', models.BooleanField(default=False, verbose_name='Bonus')),
                ('is_bonus_comment', models.TextField(verbose_name='Qanday turdagi bonus')),
                ('done', models.BooleanField(default=False, verbose_name='Bajarildi')),
            ],
            options={
                'verbose_name': "Amaliy mashg'ulot",
                'verbose_name_plural': "Amaliy mashg'ulotlar",
            },
        ),
    ]
