# Generated by Django 3.0.6 on 2021-12-14 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practical', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practical',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_instructor', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi"),
        ),
        migrations.AddField(
            model_name='practical',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practical_pupil', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi"),
        ),
        migrations.AddField(
            model_name='paymentforpractical',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practical_payment_pupil', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi"),
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='instruktor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_of_week_instruktor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Instruktor'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practical.CarModel', verbose_name='Avtomobil modeli'),
        ),
        migrations.AddField(
            model_name='car',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Region', verbose_name='Viloyatni tanlang'),
        ),
    ]
