# Generated by Django 3.0.6 on 2020-06-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_auto_20200623_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sort',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
