# Generated by Django 3.0.6 on 2020-06-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_auto_20200623_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('BC', 'BC'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=3, verbose_name='Toifasi'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sort',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Tartibi'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=600, verbose_name='Nomi'),
        ),
    ]
