# Generated by Django 3.0.6 on 2021-12-14 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='category/%Y-%m-%d/')),
                ('sort', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_category', to='video.Category')),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('is_free', models.BooleanField(default=True)),
                ('src', models.TextField(blank=True, max_length=5000, verbose_name='Mp4')),
                ('src2', models.TextField(blank=True, max_length=5000, verbose_name='Webm')),
                ('photo', models.ImageField(upload_to='photo/%Y-%m-%d/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('sort', models.SmallIntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_category', to='video.Category')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='rating_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='rating_likes', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.School')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='ViewComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_view_complete', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_view_complete', to='video.Video')),
            ],
            options={
                'verbose_name': "Ko'rilgan video",
                'verbose_name_plural': "Ko'rilgan videolar",
            },
        ),
        migrations.CreateModel(
            name='SignUpSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('select', models.BooleanField(default=False, verbose_name='Avtomaktab')),
                ('is_active', models.BooleanField(default=False, verbose_name="M/o'")),
                ('result', models.CharField(blank=True, max_length=255, verbose_name='Natija')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.School', verbose_name='Avtomaktab')),
                ('tuman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.District')),
                ('viloyat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Region')),
            ],
            options={
                'verbose_name': 'Qabul',
                'verbose_name_plural': 'Qabullar',
            },
        ),
        migrations.CreateModel(
            name='Nabor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('BC', 'BC'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='B', max_length=15, verbose_name='Toifasi')),
                ('phone', models.CharField(max_length=100)),
                ('phone2', models.CharField(blank=True, max_length=100)),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('passport', models.FileField(blank=True, upload_to='document/%Y-%m-%d/')),
                ('is_start', models.BooleanField(default=False)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.District')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Region')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.School', verbose_name='Avtomaktab')),
            ],
            options={
                'verbose_name': 'Nabor',
                'verbose_name_plural': 'Naborlar',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('src', models.FileField(upload_to='file/%Y-%m-%d/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_all', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=800)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.Video')),
            ],
        ),
    ]
